DROP TABLE IF EXISTS SAMPLES;

CREATE TABLE SAMPLES (TASK_ID INT PRIMARY KEY NOT NULL AUTOINCREMENT,
					  TASK_NAME TEXT,
					  METRIC REAL DEFAULT 0,
					  METRIC_UNITS TEXT,
					  LAST_UPDATED TEXT DEFAULT(datetime('now', 'localtime')));

INSERT INTO SAMPLES (TASK_NAME, METRIC_UNITS) VALUES ('ConnectTCPServer', 'ms');
INSERT INTO SAMPLES (TASK_NAME, METRIC_UNITS) VALUES ('CalculatePhysicalMemory', 'kB');